//! Build script: walk `stdlib/` and embed every `.ax` module into the crate.
//!
//! This is the single source of truth for stdlib source — the compiler carries
//! the stdlib *inside* the binary, so there is no hardcoded file list to drift
//! and no runtime disk dependency. The module path is derived from the relative
//! file path exactly as `modules::discover` does (`core/platform.ax` →
//! `core::platform`). See `docs/stdlib-loading-unification.md`.
//!
//! Also emits `STDLIB_MODULE_PATHS` — a perfect-hash set of every module path
//! the stdlib owns. This is the robust, unspoofable stdlib identity check
//! (see `docs/intrinsic-and-stdlib-identity.md` §2a).

use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let workspace_root = Path::new(&manifest_dir)
        .parent()
        .and_then(Path::parent)
        .ok_or("cannot locate workspace root from CARGO_MANIFEST_DIR")?;
    let stdlib_dir = workspace_root.join("stdlib");

    println!("cargo:rerun-if-changed={}", stdlib_dir.display());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect(&stdlib_dir, &stdlib_dir, &mut entries)?;
    // Deterministic order so generated output (and downstream HirIds) are stable.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // ── STDLIB source manifest ──────────────────────────────────────────────
    let mut out = String::from(
        "// @generated by build.rs — do not edit. Walks stdlib/ at build time.\n\
         pub static STDLIB: &[(&str, &str)] = &[\n",
    );
    for (name, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    out.push('\n');
    out.push_str("pub static STDLIB_MODULE_PATHS: phf::Set<&str> = phf::phf_set! {\n");
    // Quote each module path so `phf_set!` gets string literals.
    for (name, _path) in &entries {
        out.push_str(&format!("    {:?},\n", name));
    }
    out.push_str("};\n");

    let out_dir = std::env::var("OUT_DIR")?;
    fs::write(Path::new(&out_dir).join("stdlib_manifest.rs"), out)?;
    Ok(())
}

/// Recursively collect `(module_path, absolute_file_path)` for every `.ax` file.
fn collect(
    root: &Path,
    dir: &Path,
    out: &mut Vec<(String, PathBuf)>,
) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            collect(root, &path, out)?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("ax") {
            let rel = path.strip_prefix(root)?;
            out.push((rel_to_module_name(rel), path.clone()));
        }
    }
    Ok(())
}

/// Mirror of `modules::discover::rel_to_module_name`: strip `.ax`, skip
/// `mod`, join components with `::`.
fn rel_to_module_name(rel: &Path) -> String {
    let mut parts: Vec<String> = Vec::new();
    for component in rel.components() {
        let s = component.as_os_str().to_string_lossy();
        if let Some(stem) = s.strip_suffix(".ax") {
            if !stem.is_empty() && stem != "mod" {
                parts.push(stem.to_string());
            }
        } else {
            parts.push(s.to_string());
        }
    }
    parts.join("::")
}
