//! The embedded standard library — the single source of truth for stdlib source.
//!
//! `build.rs` walks `stdlib/` at compile time and bakes every `.ax` module into
//! this crate as `(module_path, source)` pairs. The compiler therefore carries
//! its own stdlib inside the binary: no hardcoded file list to drift, no runtime
//! disk dependency. All compilation paths load the stdlib from here (see
//! `docs/stdlib-loading-unification.md`).

// Pulls in `pub static STDLIB: &[(&str, &str)]` generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/stdlib_manifest.rs"));

/// All bundled stdlib modules as `(module_path, source)` pairs — e.g.
/// `("core::platform", "<source>")`. Sorted by module path (deterministic).
pub fn modules() -> &'static [(&'static str, &'static str)] {
    STDLIB
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]
    use super::*;
    use std::collections::BTreeSet;
    use std::path::Path;

    fn stdlib_dir() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .join("stdlib")
    }

    #[test]
    fn test_embedded_is_non_empty() {
        assert!(!modules().is_empty(), "no stdlib modules were embedded");
        // Every entry has a name and some source.
        for (name, source) in modules() {
            assert!(!name.is_empty(), "embedded module has empty name");
            assert!(
                !source.is_empty(),
                "embedded module `{name}` has empty source"
            );
        }
    }

    /// Drift guard: the embedded module set must match what the real module
    /// discovery sees on disk. If a stdlib file is added/removed/renamed and the
    /// embed somehow disagrees, this fails the build (ENFORCEMENT.md anti-drift).
    #[test]
    fn test_embedded_matches_disk() {
        let graph = axiom_modules::discover::discover_library(&stdlib_dir()).unwrap();
        // File-backed modules are exactly the ones with non-empty source;
        // discovery also registers synthetic empty-source directory modules.
        let disk: BTreeSet<String> = graph
            .topo_order()
            .iter()
            .map(|id| graph.get(*id))
            .filter(|m| !m.source.is_empty())
            .map(|m| m.name.clone())
            .collect();
        let embedded: BTreeSet<String> = modules().iter().map(|(n, _)| (*n).to_string()).collect();
        assert_eq!(
            embedded, disk,
            "embedded stdlib module set drifted from disk"
        );
    }
}
