//! The embedded standard library — the single source of truth for stdlib source.
//!
//! `build.rs` walks `source/` at compile time and bakes every `.ax` module into
//! this crate as `(module_path, source)` pairs. The compiler therefore carries
//! its own stdlib inside the binary: no hardcoded file list to drift, no runtime
//! disk dependency. All compilation paths load the stdlib from here (see
//! `docs/stdlib-loading-unification.md`).

// Pulls in `pub static STDLIB: &[(&str, &str)]` and
// `pub static STDLIB_MODULE_PATHS: phf::Set<&str>` generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/stdlib_manifest.rs"));

/// All bundled stdlib modules as `(module_path, source)` pairs — e.g.
/// `("core::platform", "<source>")`. Sorted by module path (deterministic).
pub fn modules() -> &'static [(&'static str, &'static str)] {
    STDLIB
}

/// Returns `true` if `name` is a module owned by the standard library.
/// Built at compile time from the `stdlib/` directory — unspoofable by
/// user code that creates files in a directory named `std/` or `core/`.
/// See `docs/intrinsic-and-stdlib-identity.md` §2a.
pub fn is_stdlib_module(name: &str) -> bool {
    STDLIB_MODULE_PATHS.contains(name)
}

/// The standard single-file / test module set: every embedded stdlib module
/// followed by one unnamed (`""`) user module. Pass straight to
/// `driver::check_modules` (or the CLI/IR pipeline). The empty user-module
/// name keeps IR fn-qualification identical to the old single-file path, so VM
/// goldens stay stable. This crate stays a leaf — it composes the list, the
/// caller drives the pipeline. See `docs/stdlib-loading-unification.md`.
pub fn with_main(source: &str) -> Vec<(&str, &str)> {
    let mut modules: Vec<(&str, &str)> = STDLIB.to_vec();
    modules.push(("", source));
    modules
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]
    use super::*;
    use std::collections::BTreeSet;
    use std::path::Path;

    fn stdlib_dir() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("source")
    }

    #[test]
    fn test_embedded_is_non_empty() {
        assert!(!modules().is_empty(), "no stdlib modules were embedded");
        // Every entry has a name and some source.
        for (name, source) in modules() {
            assert!(!name.is_empty(), "embedded module has empty name");
            assert!(
                !source.is_empty(),
                "embedded module `{name}` has empty source"
            );
        }
    }

    /// Drift guard: the embedded module set must match what the real module
    /// discovery sees on disk. If a stdlib file is added/removed/renamed and the
    /// embed somehow disagrees, this fails the build (ENFORCEMENT.md anti-drift).
    #[test]
    fn test_embedded_matches_disk() {
        let graph = modules::discover::discover_library(&stdlib_dir()).unwrap();
        // File-backed modules are exactly the ones with non-empty source;
        // discovery also registers synthetic empty-source directory modules.
        let disk: BTreeSet<String> = graph
            .topo_order()
            .iter()
            .map(|id| graph.get(*id))
            .filter(|m| !m.source.is_empty())
            .map(|m| m.name.clone())
            .collect();
        let embedded: BTreeSet<String> = modules().iter().map(|(n, _)| (*n).to_string()).collect();
        assert_eq!(
            embedded, disk,
            "embedded stdlib module set drifted from disk"
        );
    }
}
